/* jshint camelcase:false,quotmark:false,maxlen:500,
smarttabs:true,maxdepth:10,unused:false
*/
module.exports = (function(){
  /*
   * Generated by PEG.js 0.7.0.
   *
   * http://pegjs.majda.cz/
   */
  
  function quote(s) {
    /*
     * ECMA-262, 5th ed., 7.8.4: All characters may appear literally in a
     * string literal except for the closing quote character, backslash,
     * carriage return, line separator, paragraph separator, and line feed.
     * Any character may appear in the form of an escape sequence.
     *
     * For portability, we also escape escape all control and non-ASCII
     * characters. Note that "\0" and "\v" escape sequences are not used
     * because JSHint does not like the first and IE the second.
     */
     return '"' + s
      .replace(/\\/g, '\\\\')  // backslash
      .replace(/"/g, '\\"')    // closing quote character
      .replace(/\x08/g, '\\b') // backspace
      .replace(/\t/g, '\\t')   // horizontal tab
      .replace(/\n/g, '\\n')   // line feed
      .replace(/\f/g, '\\f')   // form feed
      .replace(/\r/g, '\\r')   // carriage return
      .replace(/[\x00-\x07\x0B\x0E-\x1F\x80-\uFFFF]/g, escape)
      + '"';
  }
  
  var result = {
    /*
     * Parses the input with a generated parser. If the parsing is successfull,
     * returns a value explicitly or implicitly specified by the grammar from
     * which the parser was generated (see |PEG.buildParser|). If the parsing is
     * unsuccessful, throws |PEG.parser.SyntaxError| describing the error.
     */
    parse: function(input, startRule) {
      var parseFunctions = {
        "html5": parse_html5,
        "doctype": parse_doctype,
        "part": parse_part,
        "EOF": parse_EOF,
        "char": parse_char,
        "entity": parse_entity,
        "amp": parse_amp,
        "lt": parse_lt,
        "gt": parse_gt,
        "_": parse__,
        "comment": parse_comment,
        "comment_text": parse_comment_text,
        "comment_text_char": parse_comment_text_char,
        "comment_end": parse_comment_end,
        "tag": parse_tag,
        "open_tag": parse_open_tag,
        "open_tag_end": parse_open_tag_end,
        "close_tag": parse_close_tag,
        "close_tag_end": parse_close_tag_end,
        "tag_start_name": parse_tag_start_name,
        "tag_close_name": parse_tag_close_name,
        "tag_string": parse_tag_string,
        "attribute": parse_attribute,
        "attr": parse_attr,
        "attribute_name": parse_attribute_name,
        "double_quoted_name": parse_double_quoted_name,
        "double_quoted_name_contents": parse_double_quoted_name_contents,
        "double_quoted_name_end": parse_double_quoted_name_end,
        "double_quoted_name_char": parse_double_quoted_name_char,
        "single_quoted_name": parse_single_quoted_name,
        "single_quoted_name_contents": parse_single_quoted_name_contents,
        "single_quoted_name_end": parse_single_quoted_name_end,
        "single_quoted_name_char": parse_single_quoted_name_char,
        "unquoted_name": parse_unquoted_name,
        "unquoted_name_char": parse_unquoted_name_char,
        "attribute_value": parse_attribute_value,
        "double_quoted_value": parse_double_quoted_value,
        "double_quoted_value_contents": parse_double_quoted_value_contents,
        "double_quoted_value_end": parse_double_quoted_value_end,
        "double_quoted_value_char": parse_double_quoted_value_char,
        "single_quoted_value": parse_single_quoted_value,
        "single_quoted_value_contents": parse_single_quoted_value_contents,
        "single_quoted_value_end": parse_single_quoted_value_end,
        "single_quoted_value_char": parse_single_quoted_value_char,
        "unquoted_value": parse_unquoted_value,
        "unquoted_value_char": parse_unquoted_value_char
      };
      
      if (startRule !== undefined) {
        if (parseFunctions[startRule] === undefined) {
          throw new Error("Invalid rule name: " + quote(startRule) + ".");
        }
      } else {
        startRule = "html5";
      }
      
      var pos = 0;
      var reportFailures = 0;
      var rightmostFailuresPos = 0;
      var rightmostFailuresExpected = [];
      
      function padLeft(input, padding, length) {
        var result = input;
        
        var padLength = length - input.length;
        for (var i = 0; i < padLength; i++) {
          result = padding + result;
        }
        
        return result;
      }
      
      function escape(ch) {
        var charCode = ch.charCodeAt(0);
        var escapeChar;
        var length;
        
        if (charCode <= 0xFF) {
          escapeChar = 'x';
          length = 2;
        } else {
          escapeChar = 'u';
          length = 4;
        }
        
        return '\\' + escapeChar + padLeft(charCode.toString(16).toUpperCase(), '0', length);
      }
      
      function matchFailed(failure) {
        if (pos < rightmostFailuresPos) {
          return;
        }
        
        if (pos > rightmostFailuresPos) {
          rightmostFailuresPos = pos;
          rightmostFailuresExpected = [];
        }
        
        rightmostFailuresExpected.push(failure);
      }
      
      function parse_html5() {
        var result0, result1, result2;
        var pos0, pos1;
        
        pos0 = pos;
        pos1 = pos;
        result0 = parse_doctype();
        if (result0 !== null) {
          result1 = parse_EOF();
          if (result1 !== null) {
            result0 = [result0, result1];
          } else {
            result0 = null;
            pos = pos1;
          }
        } else {
          result0 = null;
          pos = pos1;
        }
        if (result0 !== null) {
          result0 = (function(offset) { 
            lint.parser_warn("EMPTY_DOC", null, offset); 
          })(pos0);
        }
        if (result0 === null) {
          pos = pos0;
        }
        if (result0 === null) {
          pos0 = pos;
          result0 = parse_doctype();
          if (result0 !== null) {
            result2 = parse_part();
            if (result2 !== null) {
              result1 = [];
              while (result2 !== null) {
                result1.push(result2);
                result2 = parse_part();
              }
            } else {
              result1 = null;
            }
            if (result1 !== null) {
              result2 = parse_EOF();
              if (result2 !== null) {
                result0 = [result0, result1, result2];
              } else {
                result0 = null;
                pos = pos0;
              }
            } else {
              result0 = null;
              pos = pos0;
            }
          } else {
            result0 = null;
            pos = pos0;
          }
        }
        return result0;
      }
      
      function parse_doctype() {
        var result0, result1, result2;
        var pos0, pos1;
        
        pos0 = pos;
        pos1 = pos;
        if (input.substr(pos, 9).toLowerCase() === "<!doctype") {
          result0 = input.substr(pos, 9);
          pos += 9;
        } else {
          result0 = null;
          if (reportFailures === 0) {
            matchFailed("\"<!DOCTYPE\"");
          }
        }
        if (result0 !== null) {
          result1 = [];
          if (/^[^>]/.test(input.charAt(pos))) {
            result2 = input.charAt(pos);
            pos++;
          } else {
            result2 = null;
            if (reportFailures === 0) {
              matchFailed("[^>]");
            }
          }
          while (result2 !== null) {
            result1.push(result2);
            if (/^[^>]/.test(input.charAt(pos))) {
              result2 = input.charAt(pos);
              pos++;
            } else {
              result2 = null;
              if (reportFailures === 0) {
                matchFailed("[^>]");
              }
            }
          }
          if (result1 !== null) {
            if (/^[>]/.test(input.charAt(pos))) {
              result2 = input.charAt(pos);
              pos++;
            } else {
              result2 = null;
              if (reportFailures === 0) {
                matchFailed("[>]");
              }
            }
            if (result2 !== null) {
              result0 = [result0, result1, result2];
            } else {
              result0 = null;
              pos = pos1;
            }
          } else {
            result0 = null;
            pos = pos1;
          }
        } else {
          result0 = null;
          pos = pos1;
        }
        if (result0 !== null) {
          result0 = (function(offset, f) { 
            lint.parser_emit("DOCTYPE", f, offset);
          })(pos0, result0);
        }
        if (result0 === null) {
          pos = pos0;
        }
        if (result0 === null) {
          pos0 = pos;
          pos1 = pos;
          reportFailures++;
          if (input.substr(pos, 9).toLowerCase() === "<!doctype") {
            result0 = input.substr(pos, 9);
            pos += 9;
          } else {
            result0 = null;
            if (reportFailures === 0) {
              matchFailed("\"<!DOCTYPE\"");
            }
          }
          reportFailures--;
          if (result0 === null) {
            result0 = "";
          } else {
            result0 = null;
            pos = pos1;
          }
          if (result0 !== null) {
            result0 = (function(offset) { 
              lint.parser_warn("MISSING_DOCTYPE", null, offset); 
            })(pos0);
          }
          if (result0 === null) {
            pos = pos0;
          }
        }
        return result0;
      }
      
      function parse_part() {
        var result0;
        var pos0;
        
        result0 = parse_comment();
        if (result0 === null) {
          result0 = parse_tag();
          if (result0 === null) {
            pos0 = pos;
            result0 = parse_char();
            if (result0 !== null) {
              result0 = (function(offset, f) { 
                lint.parser_emit("CHAR", f, offset); 
              })(pos0, result0);
            }
            if (result0 === null) {
              pos = pos0;
            }
          }
        }
        return result0;
      }
      
      function parse_EOF() {
        var result0;
        var pos0;
        
        pos0 = pos;
        if (input.charCodeAt(pos) === 0) {
          result0 = "\x00";
          pos++;
        } else {
          result0 = null;
          if (reportFailures === 0) {
            matchFailed("\"\\x00\"");
          }
        }
        if (result0 !== null) {
          result0 = (function(offset) { 
            lint.parser_emit("EOF", null, offset);
          })(pos0);
        }
        if (result0 === null) {
          pos = pos0;
        }
        return result0;
      }
      
      function parse_char() {
        var result0, result1;
        var pos0, pos1;
        
        pos0 = pos;
        pos1 = pos;
        reportFailures++;
        result0 = parse_EOF();
        reportFailures--;
        if (result0 === null) {
          result0 = "";
        } else {
          result0 = null;
          pos = pos1;
        }
        if (result0 !== null) {
          if (/^[^><&]/.test(input.charAt(pos))) {
            result1 = input.charAt(pos);
            pos++;
          } else {
            result1 = null;
            if (reportFailures === 0) {
              matchFailed("[^><&]");
            }
          }
          if (result1 !== null) {
            result0 = [result0, result1];
          } else {
            result0 = null;
            pos = pos0;
          }
        } else {
          result0 = null;
          pos = pos0;
        }
        if (result0 === null) {
          result0 = parse_entity();
          if (result0 === null) {
            result0 = parse_amp();
            if (result0 === null) {
              result0 = parse_lt();
              if (result0 === null) {
                result0 = parse_gt();
              }
            }
          }
        }
        return result0;
      }
      
      function parse_entity() {
        var result0, result1, result2, result3, result4;
        var pos0;
        
        pos0 = pos;
        if (/^[&]/.test(input.charAt(pos))) {
          result0 = input.charAt(pos);
          pos++;
        } else {
          result0 = null;
          if (reportFailures === 0) {
            matchFailed("[&]");
          }
        }
        if (result0 !== null) {
          if (/^[a-z0-9]/.test(input.charAt(pos))) {
            result2 = input.charAt(pos);
            pos++;
          } else {
            result2 = null;
            if (reportFailures === 0) {
              matchFailed("[a-z0-9]");
            }
          }
          if (result2 !== null) {
            result1 = [];
            while (result2 !== null) {
              result1.push(result2);
              if (/^[a-z0-9]/.test(input.charAt(pos))) {
                result2 = input.charAt(pos);
                pos++;
              } else {
                result2 = null;
                if (reportFailures === 0) {
                  matchFailed("[a-z0-9]");
                }
              }
            }
          } else {
            result1 = null;
          }
          if (result1 !== null) {
            if (/^[;]/.test(input.charAt(pos))) {
              result2 = input.charAt(pos);
              pos++;
            } else {
              result2 = null;
              if (reportFailures === 0) {
                matchFailed("[;]");
              }
            }
            if (result2 !== null) {
              result0 = [result0, result1, result2];
            } else {
              result0 = null;
              pos = pos0;
            }
          } else {
            result0 = null;
            pos = pos0;
          }
        } else {
          result0 = null;
          pos = pos0;
        }
        if (result0 === null) {
          pos0 = pos;
          if (/^[&]/.test(input.charAt(pos))) {
            result0 = input.charAt(pos);
            pos++;
          } else {
            result0 = null;
            if (reportFailures === 0) {
              matchFailed("[&]");
            }
          }
          if (result0 !== null) {
            if (/^[#]/.test(input.charAt(pos))) {
              result1 = input.charAt(pos);
              pos++;
            } else {
              result1 = null;
              if (reportFailures === 0) {
                matchFailed("[#]");
              }
            }
            if (result1 !== null) {
              if (/^[0-9]/.test(input.charAt(pos))) {
                result3 = input.charAt(pos);
                pos++;
              } else {
                result3 = null;
                if (reportFailures === 0) {
                  matchFailed("[0-9]");
                }
              }
              if (result3 !== null) {
                result2 = [];
                while (result3 !== null) {
                  result2.push(result3);
                  if (/^[0-9]/.test(input.charAt(pos))) {
                    result3 = input.charAt(pos);
                    pos++;
                  } else {
                    result3 = null;
                    if (reportFailures === 0) {
                      matchFailed("[0-9]");
                    }
                  }
                }
              } else {
                result2 = null;
              }
              if (result2 !== null) {
                if (/^[;]/.test(input.charAt(pos))) {
                  result3 = input.charAt(pos);
                  pos++;
                } else {
                  result3 = null;
                  if (reportFailures === 0) {
                    matchFailed("[;]");
                  }
                }
                if (result3 !== null) {
                  result0 = [result0, result1, result2, result3];
                } else {
                  result0 = null;
                  pos = pos0;
                }
              } else {
                result0 = null;
                pos = pos0;
              }
            } else {
              result0 = null;
              pos = pos0;
            }
          } else {
            result0 = null;
            pos = pos0;
          }
          if (result0 === null) {
            pos0 = pos;
            if (/^[&]/.test(input.charAt(pos))) {
              result0 = input.charAt(pos);
              pos++;
            } else {
              result0 = null;
              if (reportFailures === 0) {
                matchFailed("[&]");
              }
            }
            if (result0 !== null) {
              if (/^[#]/.test(input.charAt(pos))) {
                result1 = input.charAt(pos);
                pos++;
              } else {
                result1 = null;
                if (reportFailures === 0) {
                  matchFailed("[#]");
                }
              }
              if (result1 !== null) {
                if (/^[x]/.test(input.charAt(pos))) {
                  result2 = input.charAt(pos);
                  pos++;
                } else {
                  result2 = null;
                  if (reportFailures === 0) {
                    matchFailed("[x]");
                  }
                }
                if (result2 !== null) {
                  if (/^[a-f0-9]/.test(input.charAt(pos))) {
                    result4 = input.charAt(pos);
                    pos++;
                  } else {
                    result4 = null;
                    if (reportFailures === 0) {
                      matchFailed("[a-f0-9]");
                    }
                  }
                  if (result4 !== null) {
                    result3 = [];
                    while (result4 !== null) {
                      result3.push(result4);
                      if (/^[a-f0-9]/.test(input.charAt(pos))) {
                        result4 = input.charAt(pos);
                        pos++;
                      } else {
                        result4 = null;
                        if (reportFailures === 0) {
                          matchFailed("[a-f0-9]");
                        }
                      }
                    }
                  } else {
                    result3 = null;
                  }
                  if (result3 !== null) {
                    if (/^[;]/.test(input.charAt(pos))) {
                      result4 = input.charAt(pos);
                      pos++;
                    } else {
                      result4 = null;
                      if (reportFailures === 0) {
                        matchFailed("[;]");
                      }
                    }
                    if (result4 !== null) {
                      result0 = [result0, result1, result2, result3, result4];
                    } else {
                      result0 = null;
                      pos = pos0;
                    }
                  } else {
                    result0 = null;
                    pos = pos0;
                  }
                } else {
                  result0 = null;
                  pos = pos0;
                }
              } else {
                result0 = null;
                pos = pos0;
              }
            } else {
              result0 = null;
              pos = pos0;
            }
          }
        }
        return result0;
      }
      
      function parse_amp() {
        var result0;
        var pos0;
        
        pos0 = pos;
        if (/^[&]/.test(input.charAt(pos))) {
          result0 = input.charAt(pos);
          pos++;
        } else {
          result0 = null;
          if (reportFailures === 0) {
            matchFailed("[&]");
          }
        }
        if (result0 !== null) {
          result0 = (function(offset) { 
            lint.parser_warn("ENCODE_AMP", null, offset); 
          })(pos0);
        }
        if (result0 === null) {
          pos = pos0;
        }
        return result0;
      }
      
      function parse_lt() {
        var result0, result1, result2;
        var pos0, pos1, pos2, pos3, pos4;
        
        pos0 = pos;
        pos1 = pos;
        if (/^[<]/.test(input.charAt(pos))) {
          result0 = input.charAt(pos);
          pos++;
        } else {
          result0 = null;
          if (reportFailures === 0) {
            matchFailed("[<]");
          }
        }
        if (result0 !== null) {
          pos2 = pos;
          reportFailures++;
          pos3 = pos;
          reportFailures++;
          pos4 = pos;
          result1 = [];
          result2 = parse__();
          while (result2 !== null) {
            result1.push(result2);
            result2 = parse__();
          }
          if (result1 !== null) {
            result2 = parse_tag_start_name();
            if (result2 !== null) {
              result1 = [result1, result2];
            } else {
              result1 = null;
              pos = pos4;
            }
          } else {
            result1 = null;
            pos = pos4;
          }
          reportFailures--;
          if (result1 === null) {
            result1 = "";
          } else {
            result1 = null;
            pos = pos3;
          }
          reportFailures--;
          if (result1 !== null) {
            result1 = "";
            pos = pos2;
          } else {
            result1 = null;
          }
          if (result1 !== null) {
            result0 = [result0, result1];
          } else {
            result0 = null;
            pos = pos1;
          }
        } else {
          result0 = null;
          pos = pos1;
        }
        if (result0 !== null) {
          result0 = (function(offset) { 
            lint.parser_warn("ENCODE_LT", null, offset); 
          })(pos0);
        }
        if (result0 === null) {
          pos = pos0;
        }
        if (result0 === null) {
          pos0 = pos;
          pos1 = pos;
          if (/^[<]/.test(input.charAt(pos))) {
            result0 = input.charAt(pos);
            pos++;
          } else {
            result0 = null;
            if (reportFailures === 0) {
              matchFailed("[<]");
            }
          }
          if (result0 !== null) {
            pos2 = pos;
            reportFailures++;
            pos3 = pos;
            reportFailures++;
            if (input.substr(pos, 3) === "!--") {
              result1 = "!--";
              pos += 3;
            } else {
              result1 = null;
              if (reportFailures === 0) {
                matchFailed("\"!--\"");
              }
            }
            reportFailures--;
            if (result1 === null) {
              result1 = "";
            } else {
              result1 = null;
              pos = pos3;
            }
            reportFailures--;
            if (result1 !== null) {
              result1 = "";
              pos = pos2;
            } else {
              result1 = null;
            }
            if (result1 !== null) {
              result0 = [result0, result1];
            } else {
              result0 = null;
              pos = pos1;
            }
          } else {
            result0 = null;
            pos = pos1;
          }
          if (result0 !== null) {
            result0 = (function(offset) { 
              lint.parser_warn("ENCODE_LT", null, offset); 
            })(pos0);
          }
          if (result0 === null) {
            pos = pos0;
          }
        }
        return result0;
      }
      
      function parse_gt() {
        var result0;
        var pos0;
        
        pos0 = pos;
        if (/^[>]/.test(input.charAt(pos))) {
          result0 = input.charAt(pos);
          pos++;
        } else {
          result0 = null;
          if (reportFailures === 0) {
            matchFailed("[>]");
          }
        }
        if (result0 !== null) {
          result0 = (function(offset) { 
            lint.parser_warn("ENCODE_GT", null, offset); 
          })(pos0);
        }
        if (result0 === null) {
          pos = pos0;
        }
        return result0;
      }
      
      function parse__() {
        var result0;
        
        if (/^[ \f\n\r\t\x0B\u200B\xA0\u1680\u200B\u180E\u2000\u200B\u2001\u2002\u200B\u2003\u2004\u200B\u2005\u2006\u200B\u2007\u2008\u200B\u2009\u200A\u200B\u2028\u2029\u200B\u2028\u2029\u200B\u202F\u205F\u200B\u3000]/.test(input.charAt(pos))) {
          result0 = input.charAt(pos);
          pos++;
        } else {
          result0 = null;
          if (reportFailures === 0) {
            matchFailed("[ \\f\\n\\r\\t\\x0B\\u200B\\xA0\\u1680\\u200B\\u180E\\u2000\\u200B\\u2001\\u2002\\u200B\\u2003\\u2004\\u200B\\u2005\\u2006\\u200B\\u2007\\u2008\\u200B\\u2009\\u200A\\u200B\\u2028\\u2029\\u200B\\u2028\\u2029\\u200B\\u202F\\u205F\\u200B\\u3000]");
          }
        }
        return result0;
      }
      
      function parse_comment() {
        var result0, result1, result2;
        var pos0;
        
        pos0 = pos;
        if (input.substr(pos, 4) === "<!--") {
          result0 = "<!--";
          pos += 4;
        } else {
          result0 = null;
          if (reportFailures === 0) {
            matchFailed("\"<!--\"");
          }
        }
        if (result0 !== null) {
          result1 = parse_comment_text();
          if (result1 !== null) {
            result2 = parse_comment_end();
            if (result2 !== null) {
              result0 = [result0, result1, result2];
            } else {
              result0 = null;
              pos = pos0;
            }
          } else {
            result0 = null;
            pos = pos0;
          }
        } else {
          result0 = null;
          pos = pos0;
        }
        return result0;
      }
      
      function parse_comment_text() {
        var result0, result1;
        var pos0;
        
        pos0 = pos;
        result0 = [];
        result1 = parse_comment_text_char();
        while (result1 !== null) {
          result0.push(result1);
          result1 = parse_comment_text_char();
        }
        if (result0 !== null) {
          result0 = (function(offset, f) {
            lint.parser_emit("COMMENT", f, offset);
          })(pos0, result0);
        }
        if (result0 === null) {
          pos = pos0;
        }
        return result0;
      }
      
      function parse_comment_text_char() {
        var result0, result1, result2;
        var pos0, pos1;
        
        pos0 = pos;
        pos1 = pos;
        reportFailures++;
        result0 = parse_EOF();
        reportFailures--;
        if (result0 === null) {
          result0 = "";
        } else {
          result0 = null;
          pos = pos1;
        }
        if (result0 !== null) {
          if (/^[^\-]/.test(input.charAt(pos))) {
            result1 = input.charAt(pos);
            pos++;
          } else {
            result1 = null;
            if (reportFailures === 0) {
              matchFailed("[^\\-]");
            }
          }
          if (result1 !== null) {
            result0 = [result0, result1];
          } else {
            result0 = null;
            pos = pos0;
          }
        } else {
          result0 = null;
          pos = pos0;
        }
        if (result0 === null) {
          pos0 = pos;
          if (/^[\-]/.test(input.charAt(pos))) {
            result0 = input.charAt(pos);
            pos++;
          } else {
            result0 = null;
            if (reportFailures === 0) {
              matchFailed("[\\-]");
            }
          }
          if (result0 !== null) {
            pos1 = pos;
            reportFailures++;
            result1 = parse_EOF();
            reportFailures--;
            if (result1 !== null) {
              result1 = "";
              pos = pos1;
            } else {
              result1 = null;
            }
            if (result1 !== null) {
              result0 = [result0, result1];
            } else {
              result0 = null;
              pos = pos0;
            }
          } else {
            result0 = null;
            pos = pos0;
          }
          if (result0 === null) {
            pos0 = pos;
            if (/^[\-]/.test(input.charAt(pos))) {
              result0 = input.charAt(pos);
              pos++;
            } else {
              result0 = null;
              if (reportFailures === 0) {
                matchFailed("[\\-]");
              }
            }
            if (result0 !== null) {
              if (/^[^\-]/.test(input.charAt(pos))) {
                result1 = input.charAt(pos);
                pos++;
              } else {
                result1 = null;
                if (reportFailures === 0) {
                  matchFailed("[^\\-]");
                }
              }
              if (result1 !== null) {
                result0 = [result0, result1];
              } else {
                result0 = null;
                pos = pos0;
              }
            } else {
              result0 = null;
              pos = pos0;
            }
            if (result0 === null) {
              pos0 = pos;
              if (/^[\-]/.test(input.charAt(pos))) {
                result0 = input.charAt(pos);
                pos++;
              } else {
                result0 = null;
                if (reportFailures === 0) {
                  matchFailed("[\\-]");
                }
              }
              if (result0 !== null) {
                if (/^[\-]/.test(input.charAt(pos))) {
                  result1 = input.charAt(pos);
                  pos++;
                } else {
                  result1 = null;
                  if (reportFailures === 0) {
                    matchFailed("[\\-]");
                  }
                }
                if (result1 !== null) {
                  pos1 = pos;
                  reportFailures++;
                  result2 = parse_EOF();
                  reportFailures--;
                  if (result2 !== null) {
                    result2 = "";
                    pos = pos1;
                  } else {
                    result2 = null;
                  }
                  if (result2 !== null) {
                    result0 = [result0, result1, result2];
                  } else {
                    result0 = null;
                    pos = pos0;
                  }
                } else {
                  result0 = null;
                  pos = pos0;
                }
              } else {
                result0 = null;
                pos = pos0;
              }
              if (result0 === null) {
                pos0 = pos;
                if (/^[\-]/.test(input.charAt(pos))) {
                  result0 = input.charAt(pos);
                  pos++;
                } else {
                  result0 = null;
                  if (reportFailures === 0) {
                    matchFailed("[\\-]");
                  }
                }
                if (result0 !== null) {
                  if (/^[\-]/.test(input.charAt(pos))) {
                    result1 = input.charAt(pos);
                    pos++;
                  } else {
                    result1 = null;
                    if (reportFailures === 0) {
                      matchFailed("[\\-]");
                    }
                  }
                  if (result1 !== null) {
                    if (/^[^>]/.test(input.charAt(pos))) {
                      result2 = input.charAt(pos);
                      pos++;
                    } else {
                      result2 = null;
                      if (reportFailures === 0) {
                        matchFailed("[^>]");
                      }
                    }
                    if (result2 !== null) {
                      result0 = [result0, result1, result2];
                    } else {
                      result0 = null;
                      pos = pos0;
                    }
                  } else {
                    result0 = null;
                    pos = pos0;
                  }
                } else {
                  result0 = null;
                  pos = pos0;
                }
              }
            }
          }
        }
        return result0;
      }
      
      function parse_comment_end() {
        var result0;
        var pos0, pos1;
        
        if (input.substr(pos, 3) === "-->") {
          result0 = "-->";
          pos += 3;
        } else {
          result0 = null;
          if (reportFailures === 0) {
            matchFailed("\"-->\"");
          }
        }
        if (result0 === null) {
          pos0 = pos;
          pos1 = pos;
          reportFailures++;
          result0 = parse_EOF();
          reportFailures--;
          if (result0 !== null) {
            result0 = "";
            pos = pos1;
          } else {
            result0 = null;
          }
          if (result0 !== null) {
            result0 = (function(offset) { 
              lint.parser_warn("COMMENT_UNTERMINATED", null, offset); 
            })(pos0);
          }
          if (result0 === null) {
            pos = pos0;
          }
        }
        return result0;
      }
      
      function parse_tag() {
        var result0;
        
        result0 = parse_open_tag();
        if (result0 === null) {
          result0 = parse_close_tag();
        }
        return result0;
      }
      
      function parse_open_tag() {
        var result0, result1, result2, result3, result4, result5;
        var pos0, pos1;
        
        pos0 = pos;
        pos1 = pos;
        if (input.charCodeAt(pos) === 60) {
          result0 = "<";
          pos++;
        } else {
          result0 = null;
          if (reportFailures === 0) {
            matchFailed("\"<\"");
          }
        }
        if (result0 !== null) {
          result1 = [];
          result2 = parse__();
          while (result2 !== null) {
            result1.push(result2);
            result2 = parse__();
          }
          if (result1 !== null) {
            result2 = parse_tag_start_name();
            if (result2 !== null) {
              result3 = [];
              result4 = parse_attribute();
              while (result4 !== null) {
                result3.push(result4);
                result4 = parse_attribute();
              }
              if (result3 !== null) {
                result4 = [];
                result5 = parse__();
                while (result5 !== null) {
                  result4.push(result5);
                  result5 = parse__();
                }
                if (result4 !== null) {
                  result5 = parse_open_tag_end();
                  if (result5 !== null) {
                    result0 = [result0, result1, result2, result3, result4, result5];
                  } else {
                    result0 = null;
                    pos = pos1;
                  }
                } else {
                  result0 = null;
                  pos = pos1;
                }
              } else {
                result0 = null;
                pos = pos1;
              }
            } else {
              result0 = null;
              pos = pos1;
            }
          } else {
            result0 = null;
            pos = pos1;
          }
        } else {
          result0 = null;
          pos = pos1;
        }
        if (result0 !== null) {
          result0 = (function(offset, leading, trailing) {
            if(leading.length) { 
              lint.parser_warn('TAG_LEADING_SPACE', leading, offset);
            }
            if(trailing.length) {
              lint.parser_warn('TAG_TRAILING_SPACE', trailing, offset);
            }
          })(pos0, result0[1], result0[4]);
        }
        if (result0 === null) {
          pos = pos0;
        }
        return result0;
      }
      
      function parse_open_tag_end() {
        var result0;
        var pos0, pos1;
        
        pos0 = pos;
        if (input.charCodeAt(pos) === 62) {
          result0 = ">";
          pos++;
        } else {
          result0 = null;
          if (reportFailures === 0) {
            matchFailed("\">\"");
          }
        }
        if (result0 !== null) {
          result0 = (function(offset) {
            lint.parser_emit("TAG_OPEN", null, offset);
          })(pos0);
        }
        if (result0 === null) {
          pos = pos0;
        }
        if (result0 === null) {
          pos0 = pos;
          if (input.substr(pos, 2) === "/>") {
            result0 = "/>";
            pos += 2;
          } else {
            result0 = null;
            if (reportFailures === 0) {
              matchFailed("\"/>\"");
            }
          }
          if (result0 !== null) {
            result0 = (function(offset, f) {
              lint.parser_warn("TAG_SELF_CLOSED", f, offset);
              lint.parser_emit("TAG_OPEN", f, offset);
            })(pos0, result0);
          }
          if (result0 === null) {
            pos = pos0;
          }
          if (result0 === null) {
            pos0 = pos;
            pos1 = pos;
            reportFailures++;
            result0 = parse_EOF();
            reportFailures--;
            if (result0 !== null) {
              result0 = "";
              pos = pos1;
            } else {
              result0 = null;
            }
            if (result0 !== null) {
              result0 = (function(offset) { 
                lint.parser_warn("TAG_UNTERMINATED", null, offset); 
              })(pos0);
            }
            if (result0 === null) {
              pos = pos0;
            }
          }
        }
        return result0;
      }
      
      function parse_close_tag() {
        var result0, result1, result2, result3, result4, result5;
        var pos0, pos1;
        
        pos0 = pos;
        pos1 = pos;
        if (input.substr(pos, 2) === "</") {
          result0 = "</";
          pos += 2;
        } else {
          result0 = null;
          if (reportFailures === 0) {
            matchFailed("\"</\"");
          }
        }
        if (result0 !== null) {
          result1 = [];
          result2 = parse__();
          while (result2 !== null) {
            result1.push(result2);
            result2 = parse__();
          }
          if (result1 !== null) {
            result2 = parse_tag_close_name();
            if (result2 !== null) {
              result3 = [];
              result4 = parse_attribute();
              while (result4 !== null) {
                result3.push(result4);
                result4 = parse_attribute();
              }
              if (result3 !== null) {
                result4 = [];
                result5 = parse__();
                while (result5 !== null) {
                  result4.push(result5);
                  result5 = parse__();
                }
                if (result4 !== null) {
                  result5 = parse_close_tag_end();
                  if (result5 !== null) {
                    result0 = [result0, result1, result2, result3, result4, result5];
                  } else {
                    result0 = null;
                    pos = pos1;
                  }
                } else {
                  result0 = null;
                  pos = pos1;
                }
              } else {
                result0 = null;
                pos = pos1;
              }
            } else {
              result0 = null;
              pos = pos1;
            }
          } else {
            result0 = null;
            pos = pos1;
          }
        } else {
          result0 = null;
          pos = pos1;
        }
        if (result0 !== null) {
          result0 = (function(offset, leading, attribute, trailing) {
            if(leading.length) { 
              lint.parser_warn('TAG_LEADING_SPACE', leading, offset);
            }
            if(trailing.length) {
              lint.parser_warn('TAG_TRAILING_SPACE', trailing, offset);
            }
            if(attribute.length) {
              lint.parser_warn('TAG_ATTRIBUTE_IN_CLOSE', attribute, offset);
            }
          })(pos0, result0[1], result0[3], result0[4]);
        }
        if (result0 === null) {
          pos = pos0;
        }
        return result0;
      }
      
      function parse_close_tag_end() {
        var result0;
        var pos0, pos1;
        
        if (input.charCodeAt(pos) === 62) {
          result0 = ">";
          pos++;
        } else {
          result0 = null;
          if (reportFailures === 0) {
            matchFailed("\">\"");
          }
        }
        if (result0 === null) {
          pos0 = pos;
          pos1 = pos;
          reportFailures++;
          result0 = parse_EOF();
          reportFailures--;
          if (result0 !== null) {
            result0 = "";
            pos = pos1;
          } else {
            result0 = null;
          }
          if (result0 !== null) {
            result0 = (function(offset) { 
              lint.parser_warn("TAG_UNTERMINATED", null, offset); 
            })(pos0);
          }
          if (result0 === null) {
            pos = pos0;
          }
        }
        return result0;
      }
      
      function parse_tag_start_name() {
        var result0, result1;
        var pos0, pos1, pos2;
        
        pos0 = pos;
        pos1 = pos;
        pos2 = pos;
        result0 = parse_tag_string();
        if (result0 !== null) {
          if (input.charCodeAt(pos) === 58) {
            result1 = ":";
            pos++;
          } else {
            result1 = null;
            if (reportFailures === 0) {
              matchFailed("\":\"");
            }
          }
          if (result1 !== null) {
            result0 = [result0, result1];
          } else {
            result0 = null;
            pos = pos2;
          }
        } else {
          result0 = null;
          pos = pos2;
        }
        result0 = result0 !== null ? result0 : "";
        if (result0 !== null) {
          result1 = parse_tag_string();
          if (result1 !== null) {
            result0 = [result0, result1];
          } else {
            result0 = null;
            pos = pos1;
          }
        } else {
          result0 = null;
          pos = pos1;
        }
        if (result0 !== null) {
          result0 = (function(offset, namespace, name) {
            if(namespace.length) {
              lint.parser_warn('TAG_WITH_NAMESPACE', namespace, offset);
            }
            lint.parser_emit("TAG_START", (namespace || []).concat(name), offset);
          })(pos0, result0[0], result0[1]);
        }
        if (result0 === null) {
          pos = pos0;
        }
        return result0;
      }
      
      function parse_tag_close_name() {
        var result0, result1;
        var pos0, pos1, pos2;
        
        pos0 = pos;
        pos1 = pos;
        pos2 = pos;
        result0 = parse_tag_string();
        if (result0 !== null) {
          if (input.charCodeAt(pos) === 58) {
            result1 = ":";
            pos++;
          } else {
            result1 = null;
            if (reportFailures === 0) {
              matchFailed("\":\"");
            }
          }
          if (result1 !== null) {
            result0 = [result0, result1];
          } else {
            result0 = null;
            pos = pos2;
          }
        } else {
          result0 = null;
          pos = pos2;
        }
        result0 = result0 !== null ? result0 : "";
        if (result0 !== null) {
          result1 = parse_tag_string();
          if (result1 !== null) {
            result0 = [result0, result1];
          } else {
            result0 = null;
            pos = pos1;
          }
        } else {
          result0 = null;
          pos = pos1;
        }
        if (result0 !== null) {
          result0 = (function(offset, namespace, name) {
            if(namespace.length) {
              lint.parser_warn('TAG_CLOSE_WITH_NAMESPACE', namespace, offset);
            }
            lint.parser_emit("TAG_CLOSE", (namespace || []).concat(name), offset);
          })(pos0, result0[0], result0[1]);
        }
        if (result0 === null) {
          pos = pos0;
        }
        return result0;
      }
      
      function parse_tag_string() {
        var result0, result1, result2;
        var pos0;
        
        pos0 = pos;
        if (/^[a-zA-Z]/.test(input.charAt(pos))) {
          result0 = input.charAt(pos);
          pos++;
        } else {
          result0 = null;
          if (reportFailures === 0) {
            matchFailed("[a-zA-Z]");
          }
        }
        if (result0 !== null) {
          result1 = [];
          if (/^[\-a-zA-Z0-9_.]/.test(input.charAt(pos))) {
            result2 = input.charAt(pos);
            pos++;
          } else {
            result2 = null;
            if (reportFailures === 0) {
              matchFailed("[\\-a-zA-Z0-9_.]");
            }
          }
          while (result2 !== null) {
            result1.push(result2);
            if (/^[\-a-zA-Z0-9_.]/.test(input.charAt(pos))) {
              result2 = input.charAt(pos);
              pos++;
            } else {
              result2 = null;
              if (reportFailures === 0) {
                matchFailed("[\\-a-zA-Z0-9_.]");
              }
            }
          }
          if (result1 !== null) {
            result0 = [result0, result1];
          } else {
            result0 = null;
            pos = pos0;
          }
        } else {
          result0 = null;
          pos = pos0;
        }
        return result0;
      }
      
      function parse_attribute() {
        var result0, result1;
        var pos0, pos1;
        
        pos0 = pos;
        pos1 = pos;
        result0 = [];
        result1 = parse__();
        while (result1 !== null) {
          result0.push(result1);
          result1 = parse__();
        }
        if (result0 !== null) {
          result1 = parse_attr();
          if (result1 !== null) {
            result0 = [result0, result1];
          } else {
            result0 = null;
            pos = pos1;
          }
        } else {
          result0 = null;
          pos = pos1;
        }
        if (result0 !== null) {
          result0 = (function(offset, leading) {
            if(leading.length === 0) {
              lint.parser_warn("ATTRIBUTE_MISSING_SPACE", null, offset);
            }
          })(pos0, result0[0]);
        }
        if (result0 === null) {
          pos = pos0;
        }
        return result0;
      }
      
      function parse_attr() {
        var result0, result1, result2, result3;
        var pos0, pos1;
        
        pos0 = pos;
        result0 = parse_attribute_name();
        if (result0 !== null) {
          pos1 = pos;
          result1 = parse__();
          result1 = result1 !== null ? result1 : "";
          if (result1 !== null) {
            if (input.charCodeAt(pos) === 61) {
              result2 = "=";
              pos++;
            } else {
              result2 = null;
              if (reportFailures === 0) {
                matchFailed("\"=\"");
              }
            }
            if (result2 !== null) {
              result3 = parse__();
              result3 = result3 !== null ? result3 : "";
              if (result3 !== null) {
                result1 = [result1, result2, result3];
              } else {
                result1 = null;
                pos = pos1;
              }
            } else {
              result1 = null;
              pos = pos1;
            }
          } else {
            result1 = null;
            pos = pos1;
          }
          if (result1 !== null) {
            result2 = parse_attribute_value();
            if (result2 !== null) {
              result0 = [result0, result1, result2];
            } else {
              result0 = null;
              pos = pos0;
            }
          } else {
            result0 = null;
            pos = pos0;
          }
        } else {
          result0 = null;
          pos = pos0;
        }
        if (result0 === null) {
          result0 = parse_attribute_name();
          if (result0 === null) {
            pos0 = pos;
            if (input.charCodeAt(pos) === 61) {
              result0 = "=";
              pos++;
            } else {
              result0 = null;
              if (reportFailures === 0) {
                matchFailed("\"=\"");
              }
            }
            if (result0 !== null) {
              result0 = (function(offset) { 
                lint.parser_warn("ATTRIBUTE_BAD_EQUALS", null, offset); 
              })(pos0);
            }
            if (result0 === null) {
              pos = pos0;
            }
          }
        }
        return result0;
      }
      
      function parse_attribute_name() {
        var result0, result1;
        var pos0, pos1, pos2;
        
        pos0 = pos;
        result0 = parse_double_quoted_name();
        if (result0 !== null) {
          result0 = (function(offset, q) { 
            lint.parser_warn("ATTRIBUTE_NAME_IN_DOUBLE_QUOTES", q, offset);  
          })(pos0, result0);
        }
        if (result0 === null) {
          pos = pos0;
        }
        if (result0 === null) {
          pos0 = pos;
          result0 = parse_single_quoted_name();
          if (result0 !== null) {
            result0 = (function(offset, q) { 
              lint.parser_warn("ATTRIBUTE_NAME_IN_SINGLE_QUOTES", q, offset);  
            })(pos0, result0);
          }
          if (result0 === null) {
            pos = pos0;
          }
          if (result0 === null) {
            pos0 = pos;
            pos1 = pos;
            pos2 = pos;
            result0 = parse_unquoted_name();
            if (result0 !== null) {
              if (input.charCodeAt(pos) === 58) {
                result1 = ":";
                pos++;
              } else {
                result1 = null;
                if (reportFailures === 0) {
                  matchFailed("\":\"");
                }
              }
              if (result1 !== null) {
                result0 = [result0, result1];
              } else {
                result0 = null;
                pos = pos2;
              }
            } else {
              result0 = null;
              pos = pos2;
            }
            result0 = result0 !== null ? result0 : "";
            if (result0 !== null) {
              result1 = parse_unquoted_name();
              if (result1 !== null) {
                result0 = [result0, result1];
              } else {
                result0 = null;
                pos = pos1;
              }
            } else {
              result0 = null;
              pos = pos1;
            }
            if (result0 !== null) {
              result0 = (function(offset, namespace, name) {
                if(namespace.length) {
                  lint.parser_warn('ATTRIBUTE_WITH_NAMESPACE', namespace, offset);
                }
                lint.parser_emit("ATTRIBUTE_NAME", (namespace || []).concat(name), offset);
              })(pos0, result0[0], result0[1]);
            }
            if (result0 === null) {
              pos = pos0;
            }
            if (result0 === null) {
              pos0 = pos;
              pos1 = pos;
              result0 = parse_unquoted_name();
              if (result0 !== null) {
                if (input.charCodeAt(pos) === 58) {
                  result1 = ":";
                  pos++;
                } else {
                  result1 = null;
                  if (reportFailures === 0) {
                    matchFailed("\":\"");
                  }
                }
                if (result1 !== null) {
                  result0 = [result0, result1];
                } else {
                  result0 = null;
                  pos = pos1;
                }
              } else {
                result0 = null;
                pos = pos1;
              }
              if (result0 !== null) {
                result0 = (function(offset, f) {
                  lint.parser_warn("BAD_ATTRIBUTE_NAME_TRAILING_COLON", f, offset);
                })(pos0, result0);
              }
              if (result0 === null) {
                pos = pos0;
              }
              if (result0 === null) {
                pos0 = pos;
                if (input.charCodeAt(pos) === 58) {
                  result0 = ":";
                  pos++;
                } else {
                  result0 = null;
                  if (reportFailures === 0) {
                    matchFailed("\":\"");
                  }
                }
                if (result0 !== null) {
                  result0 = (function(offset) {
                    lint.parser_warn("BAD_ATTRIBUTE_NAME_COLON", null, offset);
                  })(pos0);
                }
                if (result0 === null) {
                  pos = pos0;
                }
              }
            }
          }
        }
        return result0;
      }
      
      function parse_double_quoted_name() {
        var result0, result1, result2;
        var pos0;
        
        pos0 = pos;
        if (/^["]/.test(input.charAt(pos))) {
          result0 = input.charAt(pos);
          pos++;
        } else {
          result0 = null;
          if (reportFailures === 0) {
            matchFailed("[\"]");
          }
        }
        if (result0 !== null) {
          result1 = parse_double_quoted_name_contents();
          if (result1 !== null) {
            result2 = parse_double_quoted_name_end();
            if (result2 !== null) {
              result0 = [result0, result1, result2];
            } else {
              result0 = null;
              pos = pos0;
            }
          } else {
            result0 = null;
            pos = pos0;
          }
        } else {
          result0 = null;
          pos = pos0;
        }
        return result0;
      }
      
      function parse_double_quoted_name_contents() {
        var result0, result1;
        var pos0;
        
        pos0 = pos;
        result0 = [];
        result1 = parse_double_quoted_name_char();
        while (result1 !== null) {
          result0.push(result1);
          result1 = parse_double_quoted_name_char();
        }
        if (result0 !== null) {
          result0 = (function(offset, f) {
            lint.parser_emit("ATTRIBUTE_NAME", f, offset);
          })(pos0, result0);
        }
        if (result0 === null) {
          pos = pos0;
        }
        return result0;
      }
      
      function parse_double_quoted_name_end() {
        var result0;
        var pos0, pos1;
        
        if (/^["]/.test(input.charAt(pos))) {
          result0 = input.charAt(pos);
          pos++;
        } else {
          result0 = null;
          if (reportFailures === 0) {
            matchFailed("[\"]");
          }
        }
        if (result0 === null) {
          pos0 = pos;
          pos1 = pos;
          reportFailures++;
          result0 = parse_EOF();
          reportFailures--;
          if (result0 !== null) {
            result0 = "";
            pos = pos1;
          } else {
            result0 = null;
          }
          if (result0 !== null) {
            result0 = (function(offset) { 
              lint.parser_warn("DOUBLED_QUOTED_NAME_UNTERMINATED", null, offset); 
            })(pos0);
          }
          if (result0 === null) {
            pos = pos0;
          }
        }
        return result0;
      }
      
      function parse_double_quoted_name_char() {
        var result0, result1;
        var pos0, pos1;
        
        result0 = parse_entity();
        if (result0 === null) {
          result0 = parse_lt();
          if (result0 === null) {
            result0 = parse_gt();
            if (result0 === null) {
              pos0 = pos;
              if (/^[\\]/.test(input.charAt(pos))) {
                result0 = input.charAt(pos);
                pos++;
              } else {
                result0 = null;
                if (reportFailures === 0) {
                  matchFailed("[\\\\]");
                }
              }
              if (result0 !== null) {
                if (input.length > pos) {
                  result1 = input.charAt(pos);
                  pos++;
                } else {
                  result1 = null;
                  if (reportFailures === 0) {
                    matchFailed("any character");
                  }
                }
                if (result1 !== null) {
                  result0 = [result0, result1];
                } else {
                  result0 = null;
                  pos = pos0;
                }
              } else {
                result0 = null;
                pos = pos0;
              }
              if (result0 === null) {
                pos0 = pos;
                pos1 = pos;
                reportFailures++;
                result0 = parse_EOF();
                reportFailures--;
                if (result0 === null) {
                  result0 = "";
                } else {
                  result0 = null;
                  pos = pos1;
                }
                if (result0 !== null) {
                  if (/^[^"]/.test(input.charAt(pos))) {
                    result1 = input.charAt(pos);
                    pos++;
                  } else {
                    result1 = null;
                    if (reportFailures === 0) {
                      matchFailed("[^\"]");
                    }
                  }
                  if (result1 !== null) {
                    result0 = [result0, result1];
                  } else {
                    result0 = null;
                    pos = pos0;
                  }
                } else {
                  result0 = null;
                  pos = pos0;
                }
              }
            }
          }
        }
        return result0;
      }
      
      function parse_single_quoted_name() {
        var result0, result1, result2;
        var pos0;
        
        pos0 = pos;
        if (/^[']/.test(input.charAt(pos))) {
          result0 = input.charAt(pos);
          pos++;
        } else {
          result0 = null;
          if (reportFailures === 0) {
            matchFailed("[']");
          }
        }
        if (result0 !== null) {
          result1 = parse_single_quoted_name_contents();
          if (result1 !== null) {
            result2 = parse_single_quoted_name_end();
            if (result2 !== null) {
              result0 = [result0, result1, result2];
            } else {
              result0 = null;
              pos = pos0;
            }
          } else {
            result0 = null;
            pos = pos0;
          }
        } else {
          result0 = null;
          pos = pos0;
        }
        return result0;
      }
      
      function parse_single_quoted_name_contents() {
        var result0, result1;
        
        result0 = [];
        result1 = parse_single_quoted_name_char();
        while (result1 !== null) {
          result0.push(result1);
          result1 = parse_single_quoted_name_char();
        }
        return result0;
      }
      
      function parse_single_quoted_name_end() {
        var result0;
        var pos0, pos1;
        
        if (/^[']/.test(input.charAt(pos))) {
          result0 = input.charAt(pos);
          pos++;
        } else {
          result0 = null;
          if (reportFailures === 0) {
            matchFailed("[']");
          }
        }
        if (result0 === null) {
          pos0 = pos;
          pos1 = pos;
          reportFailures++;
          result0 = parse_EOF();
          reportFailures--;
          if (result0 !== null) {
            result0 = "";
            pos = pos1;
          } else {
            result0 = null;
          }
          if (result0 !== null) {
            result0 = (function(offset) { 
              lint.parser_warn("SINGLE_QUOTED_NAME_UNTERMINATED", null, offset); 
            })(pos0);
          }
          if (result0 === null) {
            pos = pos0;
          }
        }
        return result0;
      }
      
      function parse_single_quoted_name_char() {
        var result0, result1;
        var pos0, pos1;
        
        result0 = parse_entity();
        if (result0 === null) {
          result0 = parse_lt();
          if (result0 === null) {
            result0 = parse_gt();
            if (result0 === null) {
              pos0 = pos;
              if (/^[\\]/.test(input.charAt(pos))) {
                result0 = input.charAt(pos);
                pos++;
              } else {
                result0 = null;
                if (reportFailures === 0) {
                  matchFailed("[\\\\]");
                }
              }
              if (result0 !== null) {
                if (input.length > pos) {
                  result1 = input.charAt(pos);
                  pos++;
                } else {
                  result1 = null;
                  if (reportFailures === 0) {
                    matchFailed("any character");
                  }
                }
                if (result1 !== null) {
                  result0 = [result0, result1];
                } else {
                  result0 = null;
                  pos = pos0;
                }
              } else {
                result0 = null;
                pos = pos0;
              }
              if (result0 === null) {
                pos0 = pos;
                pos1 = pos;
                reportFailures++;
                result0 = parse_EOF();
                reportFailures--;
                if (result0 === null) {
                  result0 = "";
                } else {
                  result0 = null;
                  pos = pos1;
                }
                if (result0 !== null) {
                  if (/^[^']/.test(input.charAt(pos))) {
                    result1 = input.charAt(pos);
                    pos++;
                  } else {
                    result1 = null;
                    if (reportFailures === 0) {
                      matchFailed("[^']");
                    }
                  }
                  if (result1 !== null) {
                    result0 = [result0, result1];
                  } else {
                    result0 = null;
                    pos = pos0;
                  }
                } else {
                  result0 = null;
                  pos = pos0;
                }
              }
            }
          }
        }
        return result0;
      }
      
      function parse_unquoted_name() {
        var result0, result1;
        
        result1 = parse_unquoted_name_char();
        if (result1 !== null) {
          result0 = [];
          while (result1 !== null) {
            result0.push(result1);
            result1 = parse_unquoted_name_char();
          }
        } else {
          result0 = null;
        }
        return result0;
      }
      
      function parse_unquoted_name_char() {
        var result0, result1;
        var pos0, pos1;
        
        pos0 = pos;
        if (/^[\/]/.test(input.charAt(pos))) {
          result0 = input.charAt(pos);
          pos++;
        } else {
          result0 = null;
          if (reportFailures === 0) {
            matchFailed("[\\/]");
          }
        }
        if (result0 !== null) {
          pos1 = pos;
          reportFailures++;
          if (/^[>]/.test(input.charAt(pos))) {
            result1 = input.charAt(pos);
            pos++;
          } else {
            result1 = null;
            if (reportFailures === 0) {
              matchFailed("[>]");
            }
          }
          reportFailures--;
          if (result1 === null) {
            result1 = "";
          } else {
            result1 = null;
            pos = pos1;
          }
          if (result1 !== null) {
            result0 = [result0, result1];
          } else {
            result0 = null;
            pos = pos0;
          }
        } else {
          result0 = null;
          pos = pos0;
        }
        if (result0 === null) {
          pos0 = pos;
          if (/^[<]/.test(input.charAt(pos))) {
            result0 = input.charAt(pos);
            pos++;
          } else {
            result0 = null;
            if (reportFailures === 0) {
              matchFailed("[<]");
            }
          }
          if (result0 !== null) {
            result0 = (function(offset) { 
                lint.parser_warn("ATTRIBUTE_NAME_BAD_LT", null, offset); 
              })(pos0);
          }
          if (result0 === null) {
            pos = pos0;
          }
          if (result0 === null) {
            pos0 = pos;
            if (/^[&]/.test(input.charAt(pos))) {
              result0 = input.charAt(pos);
              pos++;
            } else {
              result0 = null;
              if (reportFailures === 0) {
                matchFailed("[&]");
              }
            }
            if (result0 !== null) {
              result0 = (function(offset) { lint.parser_warn("ATTRIBUTE_NAME_BAD_AMP", null, offset); 
                })(pos0);
            }
            if (result0 === null) {
              pos = pos0;
            }
            if (result0 === null) {
              pos0 = pos;
              pos1 = pos;
              reportFailures++;
              result0 = parse_EOF();
              reportFailures--;
              if (result0 === null) {
                result0 = "";
              } else {
                result0 = null;
                pos = pos1;
              }
              if (result0 !== null) {
                if (/^[^:\/>="' \f\n\r\t\x0B\u200B\xA0\u1680\u200B\u180E\u2000\u200B\u2001\u2002\u200B\u2003\u2004\u200B\u2005\u2006\u200B\u2007\u2008\u200B\u2009\u200A\u200B\u2028\u2029\u200B\u2028\u2029\u200B\u202F\u205F\u200B\u3000]/.test(input.charAt(pos))) {
                  result1 = input.charAt(pos);
                  pos++;
                } else {
                  result1 = null;
                  if (reportFailures === 0) {
                    matchFailed("[^:\\/>=\"' \\f\\n\\r\\t\\x0B\\u200B\\xA0\\u1680\\u200B\\u180E\\u2000\\u200B\\u2001\\u2002\\u200B\\u2003\\u2004\\u200B\\u2005\\u2006\\u200B\\u2007\\u2008\\u200B\\u2009\\u200A\\u200B\\u2028\\u2029\\u200B\\u2028\\u2029\\u200B\\u202F\\u205F\\u200B\\u3000]");
                  }
                }
                if (result1 !== null) {
                  result0 = [result0, result1];
                } else {
                  result0 = null;
                  pos = pos0;
                }
              } else {
                result0 = null;
                pos = pos0;
              }
            }
          }
        }
        return result0;
      }
      
      function parse_attribute_value() {
        var result0;
        var pos0;
        
        result0 = parse_double_quoted_value();
        if (result0 === null) {
          pos0 = pos;
          result0 = parse_single_quoted_value();
          if (result0 !== null) {
            result0 = (function(offset, q) { 
              lint.parser_warn("ATTRIBUTE_VALUE_IN_SINGLE_QUOTES", q, offset);  
            })(pos0, result0);
          }
          if (result0 === null) {
            pos = pos0;
          }
          if (result0 === null) {
            pos0 = pos;
            result0 = parse_unquoted_value();
            if (result0 !== null) {
              result0 = (function(offset, q) { 
                lint.parser_warn("ATTRIBUTE_VALUE_UNQUOTED", q, offset);  
              })(pos0, result0);
            }
            if (result0 === null) {
              pos = pos0;
            }
          }
        }
        return result0;
      }
      
      function parse_double_quoted_value() {
        var result0, result1, result2;
        var pos0;
        
        pos0 = pos;
        if (/^["]/.test(input.charAt(pos))) {
          result0 = input.charAt(pos);
          pos++;
        } else {
          result0 = null;
          if (reportFailures === 0) {
            matchFailed("[\"]");
          }
        }
        if (result0 !== null) {
          result1 = parse_double_quoted_value_contents();
          if (result1 !== null) {
            result2 = parse_double_quoted_value_end();
            if (result2 !== null) {
              result0 = [result0, result1, result2];
            } else {
              result0 = null;
              pos = pos0;
            }
          } else {
            result0 = null;
            pos = pos0;
          }
        } else {
          result0 = null;
          pos = pos0;
        }
        return result0;
      }
      
      function parse_double_quoted_value_contents() {
        var result0, result1;
        var pos0;
        
        pos0 = pos;
        result0 = [];
        result1 = parse_double_quoted_value_char();
        while (result1 !== null) {
          result0.push(result1);
          result1 = parse_double_quoted_value_char();
        }
        if (result0 !== null) {
          result0 = (function(offset, f) {
            lint.parser_emit("ATTRIBUTE_VALUE", f, offset);
          })(pos0, result0);
        }
        if (result0 === null) {
          pos = pos0;
        }
        return result0;
      }
      
      function parse_double_quoted_value_end() {
        var result0;
        var pos0, pos1;
        
        if (/^["]/.test(input.charAt(pos))) {
          result0 = input.charAt(pos);
          pos++;
        } else {
          result0 = null;
          if (reportFailures === 0) {
            matchFailed("[\"]");
          }
        }
        if (result0 === null) {
          pos0 = pos;
          pos1 = pos;
          reportFailures++;
          result0 = parse_EOF();
          reportFailures--;
          if (result0 !== null) {
            result0 = "";
            pos = pos1;
          } else {
            result0 = null;
          }
          if (result0 !== null) {
            result0 = (function(offset) { 
              lint.parser_warn("DOUBLED_QUOTED_VALUE_UNTERMINATED", null, offset); 
            })(pos0);
          }
          if (result0 === null) {
            pos = pos0;
          }
        }
        return result0;
      }
      
      function parse_double_quoted_value_char() {
        var result0, result1;
        var pos0, pos1;
        
        result0 = parse_entity();
        if (result0 === null) {
          result0 = parse_lt();
          if (result0 === null) {
            result0 = parse_gt();
            if (result0 === null) {
              pos0 = pos;
              if (/^[\\]/.test(input.charAt(pos))) {
                result0 = input.charAt(pos);
                pos++;
              } else {
                result0 = null;
                if (reportFailures === 0) {
                  matchFailed("[\\\\]");
                }
              }
              if (result0 !== null) {
                if (input.length > pos) {
                  result1 = input.charAt(pos);
                  pos++;
                } else {
                  result1 = null;
                  if (reportFailures === 0) {
                    matchFailed("any character");
                  }
                }
                if (result1 !== null) {
                  result0 = [result0, result1];
                } else {
                  result0 = null;
                  pos = pos0;
                }
              } else {
                result0 = null;
                pos = pos0;
              }
              if (result0 === null) {
                pos0 = pos;
                pos1 = pos;
                reportFailures++;
                result0 = parse_EOF();
                reportFailures--;
                if (result0 === null) {
                  result0 = "";
                } else {
                  result0 = null;
                  pos = pos1;
                }
                if (result0 !== null) {
                  if (/^[^"]/.test(input.charAt(pos))) {
                    result1 = input.charAt(pos);
                    pos++;
                  } else {
                    result1 = null;
                    if (reportFailures === 0) {
                      matchFailed("[^\"]");
                    }
                  }
                  if (result1 !== null) {
                    result0 = [result0, result1];
                  } else {
                    result0 = null;
                    pos = pos0;
                  }
                } else {
                  result0 = null;
                  pos = pos0;
                }
              }
            }
          }
        }
        return result0;
      }
      
      function parse_single_quoted_value() {
        var result0, result1, result2;
        var pos0;
        
        pos0 = pos;
        if (/^[']/.test(input.charAt(pos))) {
          result0 = input.charAt(pos);
          pos++;
        } else {
          result0 = null;
          if (reportFailures === 0) {
            matchFailed("[']");
          }
        }
        if (result0 !== null) {
          result1 = parse_single_quoted_value_contents();
          if (result1 !== null) {
            result2 = parse_single_quoted_value_end();
            if (result2 !== null) {
              result0 = [result0, result1, result2];
            } else {
              result0 = null;
              pos = pos0;
            }
          } else {
            result0 = null;
            pos = pos0;
          }
        } else {
          result0 = null;
          pos = pos0;
        }
        return result0;
      }
      
      function parse_single_quoted_value_contents() {
        var result0, result1;
        var pos0;
        
        pos0 = pos;
        result0 = [];
        result1 = parse_single_quoted_value_char();
        while (result1 !== null) {
          result0.push(result1);
          result1 = parse_single_quoted_value_char();
        }
        if (result0 !== null) {
          result0 = (function(offset, f) {
            lint.parser_emit("ATTRIBUTE_VALUE", f, offset);
           })(pos0, result0);
        }
        if (result0 === null) {
          pos = pos0;
        }
        return result0;
      }
      
      function parse_single_quoted_value_end() {
        var result0;
        var pos0, pos1;
        
        if (/^[']/.test(input.charAt(pos))) {
          result0 = input.charAt(pos);
          pos++;
        } else {
          result0 = null;
          if (reportFailures === 0) {
            matchFailed("[']");
          }
        }
        if (result0 === null) {
          pos0 = pos;
          pos1 = pos;
          reportFailures++;
          result0 = parse_EOF();
          reportFailures--;
          if (result0 !== null) {
            result0 = "";
            pos = pos1;
          } else {
            result0 = null;
          }
          if (result0 !== null) {
            result0 = (function(offset) { 
              lint.parser_warn("SINGLE_QUOTED_VALUE_UNTERMINATED", null, offset); 
            })(pos0);
          }
          if (result0 === null) {
            pos = pos0;
          }
        }
        return result0;
      }
      
      function parse_single_quoted_value_char() {
        var result0, result1;
        var pos0, pos1;
        
        result0 = parse_entity();
        if (result0 === null) {
          result0 = parse_lt();
          if (result0 === null) {
            result0 = parse_gt();
            if (result0 === null) {
              pos0 = pos;
              if (/^[\\]/.test(input.charAt(pos))) {
                result0 = input.charAt(pos);
                pos++;
              } else {
                result0 = null;
                if (reportFailures === 0) {
                  matchFailed("[\\\\]");
                }
              }
              if (result0 !== null) {
                if (input.length > pos) {
                  result1 = input.charAt(pos);
                  pos++;
                } else {
                  result1 = null;
                  if (reportFailures === 0) {
                    matchFailed("any character");
                  }
                }
                if (result1 !== null) {
                  result0 = [result0, result1];
                } else {
                  result0 = null;
                  pos = pos0;
                }
              } else {
                result0 = null;
                pos = pos0;
              }
              if (result0 === null) {
                pos0 = pos;
                pos1 = pos;
                reportFailures++;
                result0 = parse_EOF();
                reportFailures--;
                if (result0 === null) {
                  result0 = "";
                } else {
                  result0 = null;
                  pos = pos1;
                }
                if (result0 !== null) {
                  if (/^[^']/.test(input.charAt(pos))) {
                    result1 = input.charAt(pos);
                    pos++;
                  } else {
                    result1 = null;
                    if (reportFailures === 0) {
                      matchFailed("[^']");
                    }
                  }
                  if (result1 !== null) {
                    result0 = [result0, result1];
                  } else {
                    result0 = null;
                    pos = pos0;
                  }
                } else {
                  result0 = null;
                  pos = pos0;
                }
              }
            }
          }
        }
        return result0;
      }
      
      function parse_unquoted_value() {
        var result0, result1;
        var pos0;
        
        pos0 = pos;
        result1 = parse_unquoted_value_char();
        if (result1 !== null) {
          result0 = [];
          while (result1 !== null) {
            result0.push(result1);
            result1 = parse_unquoted_value_char();
          }
        } else {
          result0 = null;
        }
        if (result0 !== null) {
          result0 = (function(offset, f) {
            lint.parser_emit("ATTRIBUTE_VALUE", f, offset);
           })(pos0, result0);
        }
        if (result0 === null) {
          pos = pos0;
        }
        return result0;
      }
      
      function parse_unquoted_value_char() {
        var result0, result1;
        var pos0, pos1;
        
        pos0 = pos;
        if (/^[\/]/.test(input.charAt(pos))) {
          result0 = input.charAt(pos);
          pos++;
        } else {
          result0 = null;
          if (reportFailures === 0) {
            matchFailed("[\\/]");
          }
        }
        if (result0 !== null) {
          pos1 = pos;
          reportFailures++;
          if (/^[>]/.test(input.charAt(pos))) {
            result1 = input.charAt(pos);
            pos++;
          } else {
            result1 = null;
            if (reportFailures === 0) {
              matchFailed("[>]");
            }
          }
          reportFailures--;
          if (result1 === null) {
            result1 = "";
          } else {
            result1 = null;
            pos = pos1;
          }
          if (result1 !== null) {
            result0 = [result0, result1];
          } else {
            result0 = null;
            pos = pos0;
          }
        } else {
          result0 = null;
          pos = pos0;
        }
        if (result0 === null) {
          pos0 = pos;
          if (/^[<]/.test(input.charAt(pos))) {
            result0 = input.charAt(pos);
            pos++;
          } else {
            result0 = null;
            if (reportFailures === 0) {
              matchFailed("[<]");
            }
          }
          if (result0 !== null) {
            result0 = (function(offset) { 
                lint.parser_warn("ATTRIBUTE_VALUE_BAD_LT", null, offset); 
              })(pos0);
          }
          if (result0 === null) {
            pos = pos0;
          }
          if (result0 === null) {
            pos0 = pos;
            if (/^[&]/.test(input.charAt(pos))) {
              result0 = input.charAt(pos);
              pos++;
            } else {
              result0 = null;
              if (reportFailures === 0) {
                matchFailed("[&]");
              }
            }
            if (result0 !== null) {
              result0 = (function(offset) { lint.parser_warn("ATTRIBUTE_VALUE_BAD_AMP", null, offset); 
                })(pos0);
            }
            if (result0 === null) {
              pos = pos0;
            }
            if (result0 === null) {
              pos0 = pos;
              pos1 = pos;
              reportFailures++;
              result0 = parse_EOF();
              reportFailures--;
              if (result0 === null) {
                result0 = "";
              } else {
                result0 = null;
                pos = pos1;
              }
              if (result0 !== null) {
                if (/^[^\/>="' \f\n\r\t\x0B\u200B\xA0\u1680\u200B\u180E\u2000\u200B\u2001\u2002\u200B\u2003\u2004\u200B\u2005\u2006\u200B\u2007\u2008\u200B\u2009\u200A\u200B\u2028\u2029\u200B\u2028\u2029\u200B\u202F\u205F\u200B\u3000]/.test(input.charAt(pos))) {
                  result1 = input.charAt(pos);
                  pos++;
                } else {
                  result1 = null;
                  if (reportFailures === 0) {
                    matchFailed("[^\\/>=\"' \\f\\n\\r\\t\\x0B\\u200B\\xA0\\u1680\\u200B\\u180E\\u2000\\u200B\\u2001\\u2002\\u200B\\u2003\\u2004\\u200B\\u2005\\u2006\\u200B\\u2007\\u2008\\u200B\\u2009\\u200A\\u200B\\u2028\\u2029\\u200B\\u2028\\u2029\\u200B\\u202F\\u205F\\u200B\\u3000]");
                  }
                }
                if (result1 !== null) {
                  result0 = [result0, result1];
                } else {
                  result0 = null;
                  pos = pos0;
                }
              } else {
                result0 = null;
                pos = pos0;
              }
            }
          }
        }
        return result0;
      }
      
      
      function cleanupExpected(expected) {
        expected.sort();
        
        var lastExpected = null;
        var cleanExpected = [];
        for (var i = 0; i < expected.length; i++) {
          if (expected[i] !== lastExpected) {
            cleanExpected.push(expected[i]);
            lastExpected = expected[i];
          }
        }
        return cleanExpected;
      }
      
      function computeErrorPosition() {
        /*
         * The first idea was to use |String.split| to break the input up to the
         * error position along newlines and derive the line and column from
         * there. However IE's |split| implementation is so broken that it was
         * enough to prevent it.
         */
        
        var line = 1;
        var column = 1;
        var seenCR = false;
        
        for (var i = 0; i < Math.max(pos, rightmostFailuresPos); i++) {
          var ch = input.charAt(i);
          if (ch === "\n") {
            if (!seenCR) { line++; }
            column = 1;
            seenCR = false;
          } else if (ch === "\r" || ch === "\u2028" || ch === "\u2029") {
            line++;
            column = 1;
            seenCR = true;
          } else {
            column++;
            seenCR = false;
          }
        }
        
        return { line: line, column: column };
      }
      
      
      var result = parseFunctions[startRule]();
      
      /*
       * The parser is now in one of the following three states:
       *
       * 1. The parser successfully parsed the whole input.
       *
       *    - |result !== null|
       *    - |pos === input.length|
       *    - |rightmostFailuresExpected| may or may not contain something
       *
       * 2. The parser successfully parsed only a part of the input.
       *
       *    - |result !== null|
       *    - |pos < input.length|
       *    - |rightmostFailuresExpected| may or may not contain something
       *
       * 3. The parser did not successfully parse any part of the input.
       *
       *   - |result === null|
       *   - |pos === 0|
       *   - |rightmostFailuresExpected| contains at least one failure
       *
       * All code following this comment (including called functions) must
       * handle these states.
       */
      if (result === null || pos !== input.length) {
        var offset = Math.max(pos, rightmostFailuresPos);
        var found = offset < input.length ? input.charAt(offset) : null;
        var errorPosition = computeErrorPosition();
        
        throw new this.SyntaxError(
          cleanupExpected(rightmostFailuresExpected),
          found,
          offset,
          errorPosition.line,
          errorPosition.column
        );
      }
      
      return result;
    },
    
    /* Returns the parser source code. */
    toSource: function() { return this._source; }
  };
  
  /* Thrown when a parser encounters a syntax error. */
  
  result.SyntaxError = function(expected, found, offset, line, column) {
    function buildMessage(expected, found) {
      var expectedHumanized, foundHumanized;
      
      switch (expected.length) {
        case 0:
          expectedHumanized = "end of input";
          break;
        case 1:
          expectedHumanized = expected[0];
          break;
        default:
          expectedHumanized = expected.slice(0, expected.length - 1).join(", ")
            + " or "
            + expected[expected.length - 1];
      }
      
      foundHumanized = found ? quote(found) : "end of input";
      
      return "Expected " + expectedHumanized + " but " + foundHumanized + " found.";
    }
    
    this.name = "SyntaxError";
    this.expected = expected;
    this.found = found;
    this.message = buildMessage(expected, found);
    this.offset = offset;
    this.line = line;
    this.column = column;
  };
  
  result.SyntaxError.prototype = Error.prototype;
  
  return result;
})();
